# Generated by Django 5.0.3 on 2024-05-27 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_like_post_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
