# Generated by Django 5.0.3 on 2024-06-24 07:22

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_like_post_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=blog.models.upload_filepath),
        ),
        migrations.AddField(
            model_name='post',
            name='vedio',
            field=models.FileField(blank=True, upload_to=blog.models.upload_filepath),
        ),
    ]
