# Generated by Django 5.0.3 on 2024-06-24 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_image_post_vedio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='vedio',
            new_name='video',
        ),
    ]
