# Generated by Django 5.0.3 on 2024-05-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='posts',
            field=models.TextField(default=True),
        ),
    ]
